# Autogenerated wrapper script for gecko_jll for i686-linux-gnu-cxx11-julia_version+1.13.0
export libgecko, libgeckowrapper

using libcxxwrap_julia_jll
using CompilerSupportLibraries_jll
JLLWrappers.@generate_wrapper_header("gecko")
JLLWrappers.@declare_library_product(libgecko, "libgecko.so.1")
JLLWrappers.@declare_library_product(libgeckowrapper, "libgeckowrapper.so")
function __init__()
    JLLWrappers.@generate_init_header(libcxxwrap_julia_jll, CompilerSupportLibraries_jll)
    JLLWrappers.@init_library_product(
        libgecko,
        "lib/libgecko.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgeckowrapper,
        "lib/libgeckowrapper.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
